on: pull_request
name: Review
jobs:
  frontend-build:
    name: Frontend build
    runs-on: ubuntu-latest
    container: node:18
    defaults:
      run:
        working-directory: ./assets
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install modules
        run: npm install

      - name: Build production assets
        run: npm run build

  frontend-coding-standards:
    name: Frontend coding standards
    runs-on: ubuntu-latest
    container: node:18
    defaults:
      run:
        working-directory: ./assets
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install modules
        run: npm install

      - name: React coding standards
        run: npm run check-coding-standards

  changelog:
    name: Changelog should be updated
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/develop -- CHANGELOG.md && exit 1 || exit 0